<a href="https://colab.research.google.com/github/TatyanaFilimonova/Blended-Lessons/blob/main/Matrix_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
np.__version__

'1.26.4'

In [3]:
v = np.array([1, 2])
v

array([1, 2])

In [4]:
v = np.array([1, 2, 3, 4, 5], dtype = float)
v

array([1., 2., 3., 4., 5.])

In [5]:
v[0]

1.0

In [6]:
v[-1]

5.0

In [8]:
a = np.array([[1, 2, 3], [-2, 3, 4], [1, -2, 3]])
a

array([[ 1,  2,  3],
       [-2,  3,  4],
       [ 1, -2,  3]])

In [9]:
a[0, 0]

1

In [10]:
a.dtype

dtype('int64')

In [11]:
a.shape

(3, 3)

In [12]:
a.size

9

In [13]:
b = np.matrix([[-2, 1, 3], [3, -1, 4], [3, 1, 3]])
b

matrix([[-2,  1,  3],
        [ 3, -1,  4],
        [ 3,  1,  3]])

In [14]:
a_diag = np.diag(a)
a_diag

array([1, 3, 3])

In [15]:
diag_m = np.diag(a_diag)
diag_m

array([[1, 0, 0],
       [0, 3, 0],
       [0, 0, 3]])

In [16]:
np.zeros((3, 3), dtype = int)

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [18]:
np.random.randint(11, size = (4, 4))

array([[ 0,  5,  2, 10],
       [ 3,  5,  7,  6],
       [ 9, 10,  5,  7],
       [ 3,  9,  2,  7]])

In [19]:
np.ones(2)

array([1., 1.])

In [20]:
c = np.array([[1, 2, 4], [2, 1, 6], [-1, 3, 5]], dtype = float)
c

array([[ 1.,  2.,  4.],
       [ 2.,  1.,  6.],
       [-1.,  3.,  5.]])

In [21]:
np.arange(2, 9, 2)

array([2, 4, 6, 8])

In [25]:
np.linspace(0, 10, 5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [26]:
np.ones((3, 3), dtype = int)

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [27]:
a

array([[ 1,  2,  3],
       [-2,  3,  4],
       [ 1, -2,  3]])

In [28]:
a.T

array([[ 1, -2,  1],
       [ 2,  3, -2],
       [ 3,  4,  3]])

In [29]:
a.transpose()

array([[ 1, -2,  1],
       [ 2,  3, -2],
       [ 3,  4,  3]])

In [30]:
a

array([[ 1,  2,  3],
       [-2,  3,  4],
       [ 1, -2,  3]])

In [31]:
np.linalg.det(a)

40.000000000000014

In [32]:
np.linalg.det(b)

34.99999999999999

In [33]:
3*a

array([[ 3,  6,  9],
       [-6,  9, 12],
       [ 3, -6,  9]])

In [35]:
a

array([[ 1,  2,  3],
       [-2,  3,  4],
       [ 1, -2,  3]])

In [36]:
b

matrix([[-2,  1,  3],
        [ 3, -1,  4],
        [ 3,  1,  3]])

In [34]:
a + b

matrix([[-1,  3,  6],
        [ 1,  2,  8],
        [ 4, -1,  6]])

In [37]:
a - b

matrix([[ 3,  1,  0],
        [-5,  4,  0],
        [-2, -3,  0]])

In [39]:
np.dot(a, b)

matrix([[13,  2, 20],
        [25, -1, 18],
        [ 1,  6,  4]])

In [40]:
a*b

matrix([[13,  2, 20],
        [25, -1, 18],
        [ 1,  6,  4]])

In [41]:
a

array([[ 1,  2,  3],
       [-2,  3,  4],
       [ 1, -2,  3]])

In [42]:
np.linalg.inv(a)

array([[ 4.25000000e-01, -3.00000000e-01, -2.50000000e-02],
       [ 2.50000000e-01,  1.58603289e-17, -2.50000000e-01],
       [ 2.50000000e-02,  1.00000000e-01,  1.75000000e-01]])