<a href="https://colab.research.google.com/github/TatyanaFilimonova/Blended-Lessons/blob/main/%D0%A2%D0%B5%D0%BC%D0%B0_4_%D0%97%D0%BD%D0%B0%D0%B9%D0%BE%D0%BC%D1%81%D1%82%D0%B2%D0%BE_%D0%B7_DS_%D0%A3%D1%80%D0%BE%D0%BA_1_%D0%9C%D0%B0%D1%82%D1%80%D0%B8%D1%86%D1%96.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
np.__version__

'2.0.2'

1. Створи матрицю 3*3, заповни її цілими випадковими числами від 1 до 5

In [ ]:
matrix = np.random.randint(1, 6, size=(3, 3))

matrix

array([[1, 4, 2],
       [5, 1, 3],
       [5, 1, 4]])

2. Обчислити визначник матриці

In [ ]:
det = np.linalg.det(matrix)
det

np.float64(-18.999999999999996)

3. Знайти добуток всіх елементів матриці

In [ ]:
product = np.prod(matrix)
product

np.int64(2400)

In [ ]:
prod_1 = np.prod(matrix[0])
prod_2 = np.prod(matrix[1])
prod_3 = np.prod(matrix[2])
prod_1*prod_2*prod_3

np.int64(2400)

4. Знайти суму всіх елементів матриці

In [ ]:
sum = np.sum(matrix)

sum

np.int64(26)

5. Обчислити найбільший, найменший елементи

In [ ]:
max_element = np.max(matrix)

print("Найбільший елемент матриці:", max_element)

min_element = np.min(matrix)

print("Найменший елемент матриці:", min_element)

Найбільший елемент матриці: 5
Найменший елемент матриці: 1


6. Знайти середнє значення елементів матриці

In [ ]:
mean = np.mean(matrix)

print("Середнє значення елементів матриці:", mean)

Середнє значення елементів матриці: 2.888888888888889


7. Знайти матрицю, що складена з квадратних коренів.

In [ ]:
sqrt_matrix = np.sqrt(matrix)

print("Матриця квадратних коренів:")
print(sqrt_matrix)

Матриця квадратних коренів:
[[1.         2.         1.41421356]
 [2.23606798 1.         1.73205081]
 [2.23606798 1.         2.        ]]


8. Обчислити суму елементів кожного рядка. Відповідь записати  як вектор-стовпчик

In [ ]:
row_sums = np.sum(matrix, axis=1).reshape(-1, 1)

print("Сума елементів кожного рядка:")
print(row_sums)
#В результаті отримали вектор - стовпчик

Сума елементів кожного рядка:
[[ 7]
 [ 9]
 [10]]


9. Створити вектор, що містить 25 елементів. Заповнити числами від 0 до 9. Відсортувати числа за спаданням.

In [ ]:
vector = np.random.randint(0, 10, size=25)

print("Початковий вектор:")
print(vector)

# Сортуємо числа за спаданням
sorted_vector = np.sort(vector)[::-1]

print("Вектор після сортування за спаданням:")
print(sorted_vector)

Початковий вектор:
[3 6 4 4 4 8 9 4 7 7 5 9 8 2 9 5 5 6 3 5 9 7 1 8 3]
Вектор після сортування за спаданням:
[9 9 9 9 8 8 8 7 7 7 6 6 5 5 5 5 4 4 4 4 3 3 3 2 1]


10. Знайти моду, медіану, середнє, максимальне, мінімальне значення

In [ ]:
from scipy import stats
# Знаходимо моду
mode = stats.mode(vector)

# Знаходимо медіану
median = np.median(vector)

# Знаходимо середнє
mean = np.mean(vector)

# Знаходимо максимальне значення
max_value = np.max(vector)

# Знаходимо мінімальне значення
min_value = np.min(vector)

print("Мода:", mode )
print("Медіана:", median)
print("Середнє:", mean)
print("Максимальне значення:", max_value)
print("Мінімальне значення:", min_value)

Мода: ModeResult(mode=np.int64(4), count=np.int64(4))
Медіана: 5.0
Середнє: 5.64
Максимальне значення: 9
Мінімальне значення: 1


11. Створити дві матриці 4*4, заповнені числами від 1 до 10. Обчислити суму, різницю, поелементний добуток, частку.

In [ ]:
# Створюємо дві матриці 4x4 із випадкових цілих чисел від 1 до 10
matrix1 = np.random.randint(1, 11, size=(4, 4))
matrix2 = np.random.randint(1, 11, size=(4, 4))

print("Матриця 1:")
print(matrix1)

print("\nМатриця 2:")
print(matrix2)

Матриця 1:
[[ 7  3  5  2]
 [ 1  4  8  4]
 [ 5  2  8  1]
 [ 8  9  8 10]]

Матриця 2:
[[ 2  7  6  5]
 [10 10  2  8]
 [10  3  8  4]
 [ 6  3  2  1]]


In [ ]:
# Обчислюємо суму матриць
matrix_sum = matrix1 + matrix2

# Обчислюємо різницю матриць
matrix_diff = matrix1 - matrix2

# Обчислюємо поелементний добуток матриць
matrix_product = matrix1 * matrix2

# Обчислюємо поелементну частку матриць
# Для запобігання ділення на нуль, використовуємо np.divide з параметром where
matrix_division = np.divide(matrix1, matrix2, where=(matrix2!=0))

print("\nСума матриць:")
print(matrix_sum)

print("\nРізниця матриць:")
print(matrix_diff)

print("\nПоелементний добуток матриць:")
print(matrix_product)


Сума матриць:
[[14 13 11  9]
 [ 8  7  3 12]
 [14  9 14 14]
 [16 15  9 11]]

Різниця матриць:
[[ 6 -7  9 -5]
 [ 2 -3 -1 -2]
 [ 6 -1 -4 -6]
 [ 0 -5  5  9]]

Поелементний добуток матриць:
[[40 30 10 14]
 [15 10  2 35]
 [40 20 45 40]
 [64 50 14 10]]


12. Задати вектор-рядок, що містить дійсні числа 0.0-8.0. Зробити матрицю 3*3.Помножити на вектор-рядок, що містить числа 0.0-2.0

In [ ]:
x = np.arange(9.0)
x

array([0., 1., 2., 3., 4., 5., 6., 7., 8.])

In [ ]:
x1 = x.reshape((3, 3))
x1

array([[0., 1., 2.],
       [3., 4., 5.],
       [6., 7., 8.]])

In [ ]:
x2 = np.arange(3.0)
x2

array([0., 1., 2.])

In [ ]:
np.multiply(x1, x2)

array([[ 0.,  1.,  4.],
       [ 0.,  4., 10.],
       [ 0.,  7., 16.]])

13. Задати вектор-рядок (числа 0-5). Обчислити вектор в кубі.

In [ ]:
x1 = np.arange(6)
x1

array([0, 1, 2, 3, 4, 5])

In [ ]:
np.power(x1, 3)

array([  0,   1,   8,  27,  64, 125])

14. Піднести до ступеня

In [ ]:
x2 = np.array([1, 2, 3, 3, 2, 1])
x1 = np.arange(6)
x1 ** x2

array([ 0,  1,  8, 27, 16,  5])